Реализация подхода классификации документов через создание конечного набора кластеров по эмбеддингам текстов и интерпретация названий с помощью LLM

## Импорт библиотек

In [1]:
pip install -q -U langchain-huggingface langchain-core bertopic bitsandbytes>=0.46.1 natasha optuna gensim

In [2]:
# Базовые библиотеки, утилиты и работа с путями
import os
import re
import gc
import time
import ast
import textwrap
import logging
import warnings
import subprocess
import threading
from typing import List
from tqdm import tqdm

# Обработка данных
import numpy as np
import pandas as pd

# Машинное обучение и предобработка
from sklearn import metrics
from sklearn.metrics import silhouette_score
from gensim.corpora.dictionary import Dictionary
from gensim.models.coherencemodel import CoherenceModel
from sklearn.metrics import adjusted_rand_score
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import CountVectorizer

# Векторизация, кластеризация и оптимизация
import umap
import optuna
import hdbscan
from hdbscan.validity import validity_index
from sentence_transformers import SentenceTransformer

# Тематическое моделирование (BERTopic)
from bertopic import BERTopic
from bertopic.vectorizers import ClassTfidfTransformer
from bertopic.representation import MaximalMarginalRelevance

# Обработка естественного языка (NLP) - Natasha и NLTK
import nltk
from nltk.corpus import stopwords

# Deep Learning, LLM и LangChain
import torch
from transformers import (
    pipeline,
    AutoTokenizer,
    AutoModelForCausalLM,
    AutoModelForImageTextToText,
    BitsAndBytesConfig
)
from langchain_huggingface import HuggingFacePipeline
from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Google Drive (для использования в Google Colab)
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Функции

In [3]:
def get_topic(text: str) -> str:
    """Определяет краткую тему документа с помощью языковой модели.

    Аргументы:
        text (str): Исходный текст документа (приказ, служебная записка и др.).

    Возвращает:
        str: Выделенная тема документа (2-5 слов в нижнем регистре)
             или сообщение об ошибке/пустом значении.
    """
    if not text or pd.isna(text):
        return "пусто"

    try:
        # Запуск генерации через LangChain
        response = chain.invoke({"document_text": str(text)})

        # Пост-обработка: удаление случайных кавычек, точек и приведение к нижнему регистру
        return response.strip().strip('".').lower()

    except Exception as e:
        return f"ошибка: {e}"

In [4]:
def calculate_clustering_metrics(embeddings: np.ndarray, labels: np.ndarray) -> None:
    """Вычисляет и выводит ключевые метрики качества кластеризации.

    Аргументы:
        embeddings (np.ndarray): Матрица векторных представлений (эмбеддингов).
        labels (np.ndarray): Массив меток кластеров, полученных от алгоритма.
    """
    labels_arr = np.array(labels)

    # Создаем маску для НЕ-шума
    mask = labels_arr >= 0

    clean_embeddings = embeddings[mask]
    clean_labels = labels_arr[mask]

    # Статистика шума
    total_points = len(labels_arr)
    n_noise = np.sum(labels_arr == -1)
    pct_noise = (n_noise / total_points) * 100

    # Уникальные кластеры без шума
    unique_clusters = np.unique(clean_labels)
    n_clusters = len(unique_clusters)

    print(f"Кол-во тем: {n_clusters}")
    print(f"Шум: {n_noise} из {total_points} ({pct_noise:.1f}%)")

    # Проверка условий: минимум 2 кластера и хотя бы по паре точек в них
    if n_clusters > 1 and len(clean_labels) > n_clusters:
        try:
            sil = metrics.silhouette_score(clean_embeddings, clean_labels)
            ch = metrics.calinski_harabasz_score(clean_embeddings, clean_labels)
            db = metrics.davies_bouldin_score(clean_embeddings, clean_labels)

            print(f"Silhouette: {sil:.3f}")
            print(f"Calinski-Harabasz: {ch:.0f}")
            print(f"Davies-Bouldin: {db:.3f}")
        except Exception as e:
            print(f"Ошибка при расчете: {e}")
    else:
        print("Расчет невозможен: недостаточно кластеров или точек в них.")

In [5]:
def clean_noise(text: str) -> str:
    """Очищает текст от технического шума, ссылок, дат, телефонов и тегов.

    Аргументы:
        text (str): Исходная текстовая строка для очистки.

    Возвращает:
        str: Очищенная строка без лишних символов и пробелов.
    """
    if not isinstance(text, str):
        return ""

    # Удаляем URL-адреса и ссылки
    text = re.sub(r"https?://\S+|www\.\S+", "", text)

    # Удаляем Email-адреса
    text = re.sub(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b", "", text)

    # Удаляем HTML-теги
    text = re.sub(r"<.*?>", "", text)

    # Удаляем даты
    text = re.sub(r"\b\d{2}[-./]\d{2}[-./]\d{4}\b", "", text)
    text = re.sub(r"\b\d{4}[-./]\d{2}[-./]\d{2}\b", "", text)

    # Удаляем номера телефонов
    text = re.sub(
        r"\+?\d{1,3}[-.\s]?\(?\d{1,4}\)?[-.\s]?\d{1,4}[-.\s]?\d{1,4}[-.\s]?\d{1,9}",
        "",
        text,
    )

    # Заменяем b2b-разделители на пробелы
    text = re.sub(r"[_—–─]{2,}", " ", text)

    # Удаляем повторяющиеся знаки препинания
    text = re.sub(r"([!?.])\1+", r"\1", text)

    # Схлопываем множественные пробелы и переносы строк
    text = re.sub(r"\s+", " ", text)

    return text.strip().lower()

In [6]:
# Инициализация компонентов Natasha
from natasha import (
    Segmenter,
    MorphVocab,
    NewsEmbedding,
    NewsMorphTagger,
    NewsSyntaxParser,
    Doc
)

segmenter = Segmenter()
morph_vocab = MorphVocab()
emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)

# Инициализация компонентов Natasha
segmenter = Segmenter()
morph_vocab = MorphVocab()
emb = NewsEmbedding()
morph_tagger = NewsMorphTagger(emb)

def clean_single_text_lemma(text: str, stop_words) -> str:
    """
    Лемматизирует и очищает ОДИН текст (строку).
    Возвращает очищенную строку с леммами через пробел.
    """
    if not isinstance(text, str) or not text.strip():
        return ""
    text_only_letters = re.sub(r'[^а-яА-Яa-zA-Z\s]', ' ', text)
    doc = Doc(text_only_letters)
    doc.segment(segmenter)
    doc.tag_morph(morph_tagger)

    doc_lemmas = []
    for token in doc.tokens:
        token.lemmatize(morph_vocab)
        lemma = token.lemma.lower()

        # Фильтрация шума (поиск по set происходит мгновенно)
        if (lemma not in stop_words
                and token.pos != "PUNCT"
                and not lemma.isdigit()
                and len(lemma) > 2):
            doc_lemmas.append(lemma)

    # Возвращаем склеенную строку лемм
    return " ".join(doc_lemmas) if doc_lemmas else ""

In [7]:
def objective(trial: optuna.Trial, embed_norm: np.ndarray) -> float:
    n_neighbors = trial.suggest_categorical("n_neighbors", [5, 10, 20, 30, 50, 70, 100])
    n_components = trial.suggest_categorical("n_components", [3, 5, 10, 15, 20, 30, 50])
    min_dist = trial.suggest_float("min_dist", 0.0, 0.1)

    min_cluster_size = trial.suggest_categorical("min_cluster_size", [5, 10, 20, 30, 50, 70])
    min_samples = trial.suggest_categorical("min_samples", [2, 3, 5, 10, 15, 25])

    try:
        # Обучаем UMAP
        umap_embeddings = umap.UMAP(
            n_neighbors=n_neighbors,
            n_components=n_components,
            min_dist=min_dist,
            random_state=42
        ).fit_transform(embed_norm)

        # Обучаем HDBSCAN
        clusterer = hdbscan.HDBSCAN(
            min_cluster_size=min_cluster_size,
            min_samples=min_samples,
            metric='euclidean',
            cluster_selection_method='leaf',
            prediction_data=True
        ).fit(umap_embeddings)

        labels = clusterer.labels_
        mask = labels != -1
        n_clusters = len(set(labels[mask]))
        outlier_perc = np.mean(labels == -1)

        # проверка на минимальное количество кластеров
        if n_clusters < 2:
            print(f"Trial {trial.number}: [Пропущен] Мало кластеров ({n_clusters})")
            return -1.0

        # защита от избыточного шума (более 75%)
        if outlier_perc > 0.75:
            print(f"Trial {trial.number}: [Пропущен] Слишком много шума ({outlier_perc:.1%})")
            return -1.0

        # считаем на отфильтрованных ядрах кластеров
        score = silhouette_score(umap_embeddings[mask], labels[mask])

        # Лог процесса
        print(f"Trial {trial.number}: Silhouette={score:.4f} | Кластеров={n_clusters} | Шум={outlier_perc:.1%} | NN={n_neighbors}, MC={min_cluster_size}")

        return score

    except Exception as e:
        print(f"Trial {trial.number}: Ошибка во время выполнения -> {e}")
        return -1.0

## Загрузка данных

In [8]:
df = pd.read_csv('/content/drive/MyDrive/TextClust/texts.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   document_text  1000 non-null   object
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

## Получение эмбеддингов

In [ ]:
embed_model = SentenceTransformer('BAAI/bge-m3')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

In [ ]:
# Пакетная генерация эмбеддингов
texts_to_encode = [item for item in df['document_text_preproc']]
embeddings = embed_model.encode(
    texts_to_encode,
    batch_size=16,
    show_progress_bar=True,
    convert_to_numpy=True
)

Batches:   0%|          | 0/63 [00:00<?, ?it/s]

In [ ]:
# Создаем DataFrame из двух колонок
df_output = pd.DataFrame({'document_text_preproc': texts_to_encode})
df_output['embedding'] = list(embeddings)

df_output.to_feather('/content/drive/MyDrive/TextClust/document_texts_and_embeddings.feather')

print(f"Сохранено чанков: {len(df_output)}")

Сохранено чанков: 1000

In [ ]:
pd.set_option('display.max_colwidth', 500)
df_output

,document_text_preproc,embedding
0,"ПРИКАЗ №101. О проведении внепланового ТО станков ЧПУ в цехе №3. В связи с отклонением точности обработки, ПРИКАЗЫВАЮ: 1. Главному инженеру организовать проверку геометрии станков до 15.10. 2. Начальнику цеха приостановить работы на участках №2 и №4.","[-0.024791837, -0.008809981, -0.013596547, -0.0020596932, -0.020105492, -0.032709755, -0.03583683, 0.017604059, -0.013942341, 0.032927442, -0.017972875, -0.02394282, 0.0385142, 0.0037623923, -0.019265994, -0.043239534, 0.029281631, 0.007617364, 0.0029799596, -0.0008202229, 0.0061981915, -0.0018954976, 0.025457792, 0.0014714539, -0.024934076, 0.010001191, -0.013051579, -0.0058462746, 0.050871648, 0.018979715, -0.02704507, -0.018037869, 0.024075605, -0.03866371, -0.017455598, -0.039170735, 0.0..."
1,"СЛУЖЕБНАЯ ЗАПИСКА. Директору по закупкам. От нач. литейного участка. Прошу рассмотреть закупку 5 тонн чугуна СЧ20. Текущие запасы на исходе, что ставит под угрозу выполнение плана по отливке корпусов для 'МашПром'.","[0.00026988104, 0.02324181, -0.047127638, 0.0047974004, -0.006357464, -0.037006665, -0.02510175, 0.036362324, -0.0047525023, 0.0015306971, 0.027848557, -0.011987951, -0.012083356, -0.015384819, 0.0023335877, -0.058105413, -0.005835626, 0.0029501314, -0.050506715, -0.0014358809, 0.0042777746, -0.007868346, 0.05451023, 0.043815803, -0.021150054, -0.0053996677, -0.025642576, 0.012222371, 0.027984174, 0.032095723, 0.007170146, -0.017716972, 0.031525277, -0.007808531, 0.0064484808, -0.037471116, ..."
2,ИСХОДЯЩЕЕ ПИСЬМО №45/02. Руководителю ООО 'МеталлСнаб'. Уведомляем о задержке оплаты по договору №12-89 от 01.09. в связи с техническим сбоем в банке. Оплата будет произведена до конца недели. Приносим извинения.,"[-0.036639217, 0.019446326, -0.035344254, -0.004799226, -0.023842953, -0.002299977, -0.033047162, 0.015177227, -0.029074738, 0.006326412, 0.045594625, 0.009180854, 0.0028942917, 0.024371816, -0.025913268, -0.032655828, 0.0014478104, 0.0021966381, -0.002089358, 0.01224427, -0.0041722693, -0.03373229, 0.040767673, 0.007405502, 0.014572736, -0.014850345, 0.023232624, -0.013868447, 0.05055326, -0.002001114, 0.010834112, -0.00842928, 0.0003294532, -0.019455975, -0.0015054455, -0.028307091, 0.0458..."
3,"ПРИКАЗ №112. Об утверждении графика отпусков на ремонтный период. Для обеспечения работы инструментального цеха при ремонте кровли, ПРИКАЗЫВАЮ: 1. Утвердить перенос отпусков мастеров согласно приложению №1.","[-0.053496122, 0.006899469, -0.035935044, 0.0058075776, -0.019114403, -0.053256657, -0.007882538, 0.029617267, -0.010462525, -0.018215464, 0.008899451, 0.008989221, -0.017162712, 0.03549331, 0.034829397, -0.016748292, 0.05209779, 0.023153406, 0.012273234, -0.0059251464, -0.009869383, -0.036776595, 0.020597365, 0.054361243, -0.049253736, 0.01536284, -0.017487047, 0.013740337, 0.04136652, 0.0094967885, -0.0022771743, 0.0053266683, 0.018641403, 0.019776557, -0.005798334, -0.019487726, -0.009277..."
4,СЛУЖЕБНАЯ ЗАПИСКА. Главному технологу. От инженера ОТК. При приемке партии валов (чертеж ) выявлен брак по шероховатости. Прошу провести аудит техпроцесса шлиф-обработки и проверить состояние кругов.,"[-0.03445354, 0.032488752, -0.046638764, 0.0052144728, 0.014366459, -0.03712058, -0.011221448, 0.023017941, -0.019441973, 0.0018942987, 0.049564544, -0.042440876, 0.054303125, 0.007074009, 0.041578192, -0.021058558, 0.024661824, 0.019617673, -0.022267276, 0.03460966, -0.0036528907, 0.033365607, 0.036243048, -0.04357314, -0.016295146, -0.018852739, -0.018849272, 0.0034545027, 0.037076347, 0.0008628612, 0.020199979, -0.010118406, -0.01403662, -0.034476615, -0.057125684, -0.06481441, 0.05614689..."
...,...,...
995,ПРИКАЗ №2090. О проведении аттестации рабочих мест по условиям труда на новом участке ЧПУ. Организовать замеры уровня вибрации и освещенности. Срок исполнения — до 25.12. Ответственный — инж. по ОТ.,"[-0.017633798, -0.013361762, -0.024568891, -0.024850959, -0.013994071, -0.03329191, -0.024194539, -0.011773128, -0.0066081467, 0.012612093, 0.019871466, 0.0028308085, 0.021630697, 0.02263133, 0.030483633, -0.06280901, 0.023385003, -0.031131797, 0.0021433895, -0.0234122, -0.013063832, -0.03709032, 0.0069603203, 0.06166406, 0.017453937, -0.025516333, -0.004372745, 0.010920721, 0.030964237, 0.019313062, -0.00399083, 0.013348906, 0.01138863, -0.030549832, -0.016568163, -0.062686846, 0.007139763,..."
996,ИСХОДЯЩЕЕ ПИСЬМО. Руководителю службы логистики АО 'Порт'. Просим уточнить график приема крупногабаритных грузов в декабре и январе. Направляем чертежи упаковки изделия 'Рама' для согласования схемы погрузки.,"[-0.011460401, 0.008986327, -0.027952084, -0.0074157175, -0.025185907, -0.050558146, -0.03383593, -0.014070551, -0.0022767351, -0.010214109, 0.03734865, 0.0030802172, 0.01080124, 0.033565003, 0.005363039, 0.0074167666, 0.009133167, -0.02450125, -0.019466385, 0.004750793, 0.01866185, 0.001784398, -0.009600204, 0.013449939, -0.0038314434, -0.010310248, 0.012425035, -0.0018016846, 0.077383436, 0.062557645, 0.0009774801, -0.018052964, 0.022985626, -0.02344754, 0.019768465, -0.051193185, 0.032342..."
997,СЛУЖЕБНАЯ ЗАПИСКА. Директору по ИТ. От нач. отдела кадров. Прошу приобрести дополнительную лицензию на ПО '1С:Зарплата и кадры' в связи с увеличением штата сотрудников расчетной группы бухгалтерии.,"[-0.033264436, 0.028869014, -0.08007223, -0.00300456, -1.8010058e-05, -0.039604202, -0.00558081, 0.030101914, 0.03881219, -0.042665426, 0.028122842, -0.040402055, -0.014898324, 0.018404353, 0.04934067, 0.0045395065, -0.020451894, -0.004667878, -0.030621417, 0.04394719, 0.039024893, -0.010453846, 0.043112762, 0.041271422, -0.06303166, -0.020910252, -0.0058511705, 0.022516433, 0.07575127, -0.0052856803, -0.0038042285, -0.053796068, 0.042530384, -0.0070776045, -0.005056389, -0.03597361, 0.02863..."
998,"ПРИКАЗ №2095. О дисциплинарном взыскании за нарушение правил охраны труда. За работу на сверлильном станке в перчатках, объявить замечание оператору Петрову И.И. и лишить премии за текущий месяц.","[-0.019750433, 0.040950805, -0.06493365, 0.014419918, -0.013477683, -0.017651, -0.049382612, 0.025608972, 0.008712914, -0.0110002505, -0.05552245, -0.014019369, 0.009618157, -0.032037586, 0.07200555, -0.017295498, 0.03253554, -0.015953433, 0.00921914, -0.050498363, 0.017411968, 0.017208721, 0.024859041, 0.09492629, -0.02712251, -0.042595997, 0.015133382, -0.0019644634, 0.03321449, -0.025828429, -0.016889196, -0.009185188, 0.0040695844, -0.057312816, -0.027502928, -0.017222568, 0.01808338, 0...."
999,СЛУЖЕБНАЯ ЗАПИСКА. Нач. ОМТС. От нач. электроцеха. Срочно требуется закупка 100 метров кабеля ВВГ 3х2.5 для монтажа дополнительного освещения на участке сборки. Отсутствие кабеля задерживает работы.,"[-0.034419008, 0.02622641, -0.055376217, 0.023916518, 0.00900758, -0.039266154, -0.005885693, 0.017984279, 0.0008226827, 0.0092290295, 0.016752096, -0.049927447, 0.024432395, -0.029807478, 0.020962438, -0.02682494, -0.01323895, -0.023156052, 0.036500182, 0.05355698, 0.034200978, 0.037904587, 0.03499713, 0.015330328, -0.008203729, 0.031459674, -0.03806726, -0.013911579, 0.016405053, -0.00045792857, -0.015583074, -0.030008875, 0.032493107, -0.023160132, -0.01020101, -0.01952652, -0.005150638, ..."

## BERTopic

In [10]:
df = pd.read_feather('/content/drive/MyDrive/TextClust/document_texts_and_embeddings.feather')

In [11]:
embed=np.stack(df['embedding'].values)
embed.shape

(1000, 1024)

In [12]:
# L2 нормализация для евклидового пространства
embed_norm = normalize(embed)

In [13]:
nltk.download('stopwords')
stop_words = stopwords.words('russian')+['гост', 'ост', 'ту', 'рис', 'табл', 'рисунок', 'таблица', 'пункт', 'тз', 'кд', 'тд', 'нтд', 'гост', 'ост', 'ниокр', 'нии', 'кб',
    'отк', 'ппр', 'то', 'тр', 'кр', 'зип', 'рэ', 'пс', 'рис', 'табл', 'см', 'мм', 'км', 'кг', 'квт', 'мпа', 'шт', 'об', 'мин', 'сек', 'оао', 'пао', 'ао', 'тоо', 'ооо', 'зао', 'фгуп', 'гуп', 'ип', 'гк', 'нп',
    'нии', 'кб', 'цкб', 'пки', 'ран', 'ниу', 'втуз', 'нпо', 'по', 'пп', 'хк','минпромторг', 'минэнерго', 'минобороны', 'мчс', 'ростех', 'росатом',
    'роскосмос', 'ржд', 'росстандарт', 'фстэк', 'записка', 'служебная', 'служебные', 'приказ', 'приказы', 'письмо', 'письма',
    'исходящее', 'исходящие', 'входящее', 'входящие', 'необходимость', 'проведение',
    'касательно', 'повод', 'поводу', 'относительно', 'справка', 'акт', 'акты',
    'протокол', 'протоколы', 'заявка', 'заявки', 'отчет', 'отчеты', 'записка']

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [14]:
vectorizer_model = CountVectorizer(
    ngram_range=(1, 2),
    min_df=1,
    stop_words=stop_words,
    token_pattern=r"(?u)\b[а-яА-ЯёЁ]{2,}\b",
)

In [15]:
ctfidf_model = ClassTfidfTransformer(
    reduce_frequent_words=False,
    bm25_weighting=True
)

In [ ]:
# Инициализация и запуск оптимизации
study = optuna.create_study(direction="maximize")
study.optimize(lambda trial: objective(trial, embed_norm), n_trials=50)

print("\nЛучшие параметры:", study.best_params)

[I 2026-05-29 19:11:22,528] A new study created in memory with name: no-name-3274dddc-b917-4fbd-b58a-7a7ea00ef567
[I 2026-05-29 19:11:28,715] Trial 0 finished with value: 0.6415014863014221 and parameters: {'n_neighbors': 10, 'n_components': 10, 'min_dist': 0.09075832272334992, 'min_cluster_size': 50, 'min_samples': 25}. Best is trial 0 with value: 0.6415014863014221.

Trial 0: Silhouette=0.6415 | Кластеров=5 | Шум=19.0% | NN=10, MC=50

[I 2026-05-29 19:11:44,455] Trial 1 finished with value: 0.4407379925251007 and parameters: {'n_neighbors': 100, 'n_components': 15, 'min_dist': 0.09230271874752657, 'min_cluster_size': 10, 'min_samples': 3}. Best is trial 0 with value: 0.6415014863014221.

Trial 1: Silhouette=0.4407 | Кластеров=39 | Шум=14.5% | NN=100, MC=10

[I 2026-05-29 19:11:55,666] Trial 2 finished with value: 0.5091317296028137 and parameters: {'n_neighbors': 30, 'n_components': 15, 'min_dist': 0.016860883223587097, 'min_cluster_size': 50, 'min_samples': 2}. Best is trial 0 with value: 0.6415014863014221.

Trial 2: Silhouette=0.5091 | Кластеров=9 | Шум=13.7% | NN=30, MC=50

[I 2026-05-29 19:12:03,081] Trial 3 finished with value: 0.5883887410163879 and parameters: {'n_neighbors': 50, 'n_components': 50, 'min_dist': 0.07416344429457554, 'min_cluster_size': 10, 'min_samples': 25}. Best is trial 0 with value: 0.6415014863014221.

Trial 3: Silhouette=0.5884 | Кластеров=13 | Шум=30.1% | NN=50, MC=10

[I 2026-05-29 19:12:09,056] Trial 4 finished with value: 0.4868992865085602 and parameters: {'n_neighbors': 100, 'n_components': 5, 'min_dist': 0.07857306252204609, 'min_cluster_size': 10, 'min_samples': 2}. Best is trial 0 with value: 0.6415014863014221.

Trial 4: Silhouette=0.4869 | Кластеров=41 | Шум=14.6% | NN=100, MC=10

[I 2026-05-29 19:12:14,094] Trial 5 finished with value: 0.479417085647583 and parameters: {'n_neighbors': 70, 'n_components': 10, 'min_dist': 0.06573870419444702, 'min_cluster_size': 70, 'min_samples': 15}. Best is trial 0 with value: 0.6415014863014221.

Trial 5: Silhouette=0.4794 | Кластеров=5 | Шум=24.1% | NN=70, MC=70

[I 2026-05-29 19:12:18,647] Trial 6 finished with value: 0.4536832869052887 and parameters: {'n_neighbors': 100, 'n_components': 3, 'min_dist': 0.031919674178762195, 'min_cluster_size': 30, 'min_samples': 5}. Best is trial 0 with value: 0.6415014863014221.

Trial 6: Silhouette=0.4537 | Кластеров=13 | Шум=12.3% | NN=100, MC=30

[I 2026-05-29 19:12:24,442] Trial 7 finished with value: 0.715869665145874 and parameters: {'n_neighbors': 10, 'n_components': 30, 'min_dist': 0.09250288662207912, 'min_cluster_size': 10, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 7: Silhouette=0.7159 | Кластеров=43 | Шум=14.7% | NN=10, MC=10

[I 2026-05-29 19:12:28,386] Trial 8 finished with value: 0.52654629945755 and parameters: {'n_neighbors': 50, 'n_components': 5, 'min_dist': 0.03455493715491368, 'min_cluster_size': 30, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 8: Silhouette=0.5265 | Кластеров=13 | Шум=9.6% | NN=50, MC=30

[I 2026-05-29 19:12:31,805] Trial 9 finished with value: 0.6664631366729736 and parameters: {'n_neighbors': 10, 'n_components': 15, 'min_dist': 8.840858804475271e-05, 'min_cluster_size': 10, 'min_samples': 2}. Best is trial 7 with value: 0.715869665145874.

Trial 9: Silhouette=0.6665 | Кластеров=55 | Шум=7.5% | NN=10, MC=10

[I 2026-05-29 19:12:36,787] Trial 10 finished with value: 0.6468257904052734 and parameters: {'n_neighbors': 5, 'n_components': 30, 'min_dist': 0.05501519018598959, 'min_cluster_size': 20, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 10: Silhouette=0.6468 | Кластеров=24 | Шум=9.5% | NN=5, MC=20

[I 2026-05-29 19:12:40,425] Trial 11 finished with value: 0.6969155669212341 and parameters: {'n_neighbors': 10, 'n_components': 20, 'min_dist': 0.0005009379827869379, 'min_cluster_size': 10, 'min_samples': 2}. Best is trial 7 with value: 0.715869665145874.

Trial 11: Silhouette=0.6969 | Кластеров=54 | Шум=8.9% | NN=10, MC=10

[I 2026-05-29 19:12:45,162] Trial 12 finished with value: 0.6991865038871765 and parameters: {'n_neighbors': 20, 'n_components': 20, 'min_dist': 0.0431284285400548, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 12: Silhouette=0.6992 | Кластеров=43 | Шум=24.8% | NN=20, MC=5

[I 2026-05-29 19:12:52,281] Trial 13 finished with value: 0.6787338852882385 and parameters: {'n_neighbors': 20, 'n_components': 30, 'min_dist': 0.04305657020253663, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 13: Silhouette=0.6787 | Кластеров=42 | Шум=22.9% | NN=20, MC=5

[I 2026-05-29 19:12:56,957] Trial 14 finished with value: 0.6927196383476257 and parameters: {'n_neighbors': 20, 'n_components': 20, 'min_dist': 0.052157292335878014, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 14: Silhouette=0.6927 | Кластеров=42 | Шум=22.3% | NN=20, MC=5

[I 2026-05-29 19:13:01,607] Trial 15 finished with value: 0.6894659399986267 and parameters: {'n_neighbors': 20, 'n_components': 20, 'min_dist': 0.0606860038502409, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 7 with value: 0.715869665145874.

Trial 15: Silhouette=0.6895 | Кластеров=42 | Шум=21.9% | NN=20, MC=5

[I 2026-05-29 19:13:12,064] Trial 16 finished with value: 0.4737744927406311 and parameters: {'n_neighbors': 70, 'n_components': 30, 'min_dist': 0.02460003959751827, 'min_cluster_size': 20, 'min_samples': 3}. Best is trial 7 with value: 0.715869665145874.

Trial 16: Silhouette=0.4738 | Кластеров=20 | Шум=11.6% | NN=70, MC=20

[I 2026-05-29 19:13:15,362] Trial 17 finished with value: 0.5553167462348938 and parameters: {'n_neighbors': 30, 'n_components': 3, 'min_dist': 0.09727941536197726, 'min_cluster_size': 70, 'min_samples': 15}. Best is trial 7 with value: 0.715869665145874.

Trial 17: Silhouette=0.5553 | Кластеров=7 | Шум=33.7% | NN=30, MC=70

[I 2026-05-29 19:13:19,367] Trial 18 finished with value: 0.7238336205482483 and parameters: {'n_neighbors': 5, 'n_components': 50, 'min_dist': 0.04233106894057385, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 18 with value: 0.7238336205482483.

Trial 18: Silhouette=0.7238 | Кластеров=79 | Шум=10.4% | NN=5, MC=5

[I 2026-05-29 19:13:23,753] Trial 19 finished with value: 0.6952067017555237 and parameters: {'n_neighbors': 5, 'n_components': 50, 'min_dist': 0.08292294395061259, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 18 with value: 0.7238336205482483.

Trial 19: Silhouette=0.6952 | Кластеров=76 | Шум=8.8% | NN=5, MC=5

[I 2026-05-29 19:13:27,199] Trial 20 finished with value: 0.6040185689926147 and parameters: {'n_neighbors': 5, 'n_components': 50, 'min_dist': 0.06495247181234466, 'min_cluster_size': 30, 'min_samples': 5}. Best is trial 18 with value: 0.7238336205482483.

Trial 20: Silhouette=0.6040 | Кластеров=15 | Шум=20.8% | NN=5, MC=30

[I 2026-05-29 19:13:32,090] Trial 21 finished with value: 0.69119793176651 and parameters: {'n_neighbors': 10, 'n_components': 30, 'min_dist': 0.044844885327739996, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 18 with value: 0.7238336205482483.

Trial 21: Silhouette=0.6912 | Кластеров=68 | Шум=11.7% | NN=10, MC=5

[I 2026-05-29 19:13:39,209] Trial 22 finished with value: 0.6818320155143738 and parameters: {'n_neighbors': 20, 'n_components': 50, 'min_dist': 0.03942854456213603, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 18 with value: 0.7238336205482483.

Trial 22: Silhouette=0.6818 | Кластеров=42 | Шум=24.8% | NN=20, MC=5

[I 2026-05-29 19:13:44,869] Trial 23 finished with value: 0.7687163949012756 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.019360479975685907, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 23 with value: 0.7687163949012756.

Trial 23: Silhouette=0.7687 | Кластеров=44 | Шум=16.9% | NN=5, MC=5

[I 2026-05-29 19:13:49,019] Trial 24 finished with value: 0.7244008779525757 and parameters: {'n_neighbors': 5, 'n_components': 30, 'min_dist': 0.012024561756679507, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 24: Silhouette=0.7244 | Кластеров=76 | Шум=7.6% | NN=5, MC=5

[I 2026-05-29 19:13:53,404] Trial 25 finished with value: 0.7209051847457886 and parameters: {'n_neighbors': 5, 'n_components': 50, 'min_dist': 0.013346681429429817, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 25: Silhouette=0.7209 | Кластеров=80 | Шум=9.2% | NN=5, MC=5

[I 2026-05-29 19:13:56,304] Trial 26 finished with value: 0.740851640701294 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.012525072114794273, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 26: Silhouette=0.7409 | Кластеров=81 | Шум=9.9% | NN=5, MC=5

[I 2026-05-29 19:13:59,168] Trial 27 finished with value: 0.73338383436203 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.014467917422881593, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 27: Silhouette=0.7334 | Кластеров=79 | Шум=8.3% | NN=5, MC=5

[I 2026-05-29 19:14:02,302] Trial 28 finished with value: 0.7368288636207581 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.021795849328004185, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 28: Silhouette=0.7368 | Кластеров=77 | Шум=8.9% | NN=5, MC=5

[I 2026-05-29 19:14:06,359] Trial 29 finished with value: 0.5540066361427307 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.025016720149846176, 'min_cluster_size': 50, 'min_samples': 25}. Best is trial 23 with value: 0.7687163949012756.

Trial 29: Silhouette=0.5540 | Кластеров=7 | Шум=23.9% | NN=5, MC=50

[I 2026-05-29 19:14:09,301] Trial 30 finished with value: 0.5180205702781677 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.021760342838336683, 'min_cluster_size': 70, 'min_samples': 3}. Best is trial 23 with value: 0.7687163949012756.

Trial 30: Silhouette=0.5180 | Кластеров=5 | Шум=31.8% | NN=5, MC=70

[I 2026-05-29 19:14:12,156] Trial 31 finished with value: 0.7492263913154602 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.007499683970145565, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 31: Silhouette=0.7492 | Кластеров=77 | Шум=9.9% | NN=5, MC=5

[I 2026-05-29 19:14:15,524] Trial 32 finished with value: 0.7481364011764526 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.0060083522027008516, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 32: Silhouette=0.7481 | Кластеров=78 | Шум=8.8% | NN=5, MC=5

[I 2026-05-29 19:14:22,797] Trial 33 finished with value: 0.5910559892654419 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.009085273196458523, 'min_cluster_size': 50, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 33: Silhouette=0.5911 | Кластеров=7 | Шум=37.6% | NN=5, MC=50

[I 2026-05-29 19:14:26,820] Trial 34 finished with value: 0.6547412276268005 and parameters: {'n_neighbors': 30, 'n_components': 10, 'min_dist': 0.006095082169433051, 'min_cluster_size': 5, 'min_samples': 25}. Best is trial 23 with value: 0.7687163949012756.

Trial 34: Silhouette=0.6547 | Кластеров=16 | Шум=25.0% | NN=30, MC=5

[I 2026-05-29 19:14:35,495] Trial 35 finished with value: 0.5642445683479309 and parameters: {'n_neighbors': 50, 'n_components': 20, 'min_dist': 0.006329548658165045, 'min_cluster_size': 20, 'min_samples': 15}. Best is trial 23 with value: 0.7687163949012756.

Trial 35: Silhouette=0.5642 | Кластеров=15 | Шум=15.6% | NN=50, MC=20

[I 2026-05-29 19:14:41,241] Trial 36 finished with value: 0.7416778802871704 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.0182710519859559, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 36: Silhouette=0.7417 | Кластеров=77 | Шум=7.4% | NN=5, MC=5

[I 2026-05-29 19:14:48,968] Trial 37 finished with value: 0.5340142250061035 and parameters: {'n_neighbors': 100, 'n_components': 20, 'min_dist': 0.031005158441390283, 'min_cluster_size': 50, 'min_samples': 3}. Best is trial 23 with value: 0.7687163949012756.

Trial 37: Silhouette=0.5340 | Кластеров=8 | Шум=30.6% | NN=100, MC=50

[I 2026-05-29 19:14:54,969] Trial 38 finished with value: 0.5500907301902771 and parameters: {'n_neighbors': 70, 'n_components': 15, 'min_dist': 0.018666985889938627, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 38: Silhouette=0.5501 | Кластеров=50 | Шум=22.4% | NN=70, MC=5

[I 2026-05-29 19:14:57,119] Trial 39 finished with value: 0.5217626690864563 and parameters: {'n_neighbors': 5, 'n_components': 5, 'min_dist': 0.004174025604520777, 'min_cluster_size': 70, 'min_samples': 25}. Best is trial 23 with value: 0.7687163949012756.

Trial 39: Silhouette=0.5218 | Кластеров=5 | Шум=17.5% | NN=5, MC=70

[I 2026-05-29 19:14:59,495] Trial 40 finished with value: 0.6576801538467407 and parameters: {'n_neighbors': 5, 'n_components': 10, 'min_dist': 0.026326345991363458, 'min_cluster_size': 30, 'min_samples': 15}. Best is trial 23 with value: 0.7687163949012756.

Trial 40: Silhouette=0.6577 | Кластеров=15 | Шум=22.8% | NN=5, MC=30

[I 2026-05-29 19:15:03,412] Trial 41 finished with value: 0.7310950756072998 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.0160103432710042, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 41: Silhouette=0.7311 | Кластеров=79 | Шум=8.3% | NN=5, MC=5

[I 2026-05-29 19:15:06,544] Trial 42 finished with value: 0.7302060723304749 and parameters: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.011194702369002218, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 42: Silhouette=0.7302 | Кластеров=78 | Шум=8.6% | NN=5, MC=5

[I 2026-05-29 19:15:08,557] Trial 43 finished with value: 0.755663275718689 and parameters: {'n_neighbors': 5, 'n_components': 3, 'min_dist': 0.018456880588673907, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 43: Silhouette=0.7557 | Кластеров=83 | Шум=9.5% | NN=5, MC=5

[I 2026-05-29 19:15:12,137] Trial 44 finished with value: 0.5799068212509155 and parameters: {'n_neighbors': 50, 'n_components': 3, 'min_dist': 0.0014173018039634541, 'min_cluster_size': 5, 'min_samples': 2}. Best is trial 23 with value: 0.7687163949012756.

Trial 44: Silhouette=0.5799 | Кластеров=79 | Шум=16.6% | NN=50, MC=5

[I 2026-05-29 19:15:17,026] Trial 45 finished with value: 0.5932689309120178 and parameters: {'n_neighbors': 100, 'n_components': 3, 'min_dist': 0.029759712354969898, 'min_cluster_size': 5, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 45: Silhouette=0.5933 | Кластеров=57 | Шум=25.0% | NN=100, MC=5

[I 2026-05-29 19:15:19,700] Trial 46 finished with value: 0.7362581491470337 and parameters: {'n_neighbors': 5, 'n_components': 3, 'min_dist': 0.01842900322580015, 'min_cluster_size': 10, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 46: Silhouette=0.7363 | Кластеров=53 | Шум=7.0% | NN=5, MC=10

[I 2026-05-29 19:15:23,119] Trial 47 finished with value: 0.5608804225921631 and parameters: {'n_neighbors': 30, 'n_components': 5, 'min_dist': 0.008886763079277847, 'min_cluster_size': 20, 'min_samples': 2}. Best is trial 23 with value: 0.7687163949012756.

Trial 47: Silhouette=0.5609 | Кластеров=21 | Шум=8.5% | NN=30, MC=20

[I 2026-05-29 19:15:28,798] Trial 48 finished with value: 0.5795047283172607 and parameters: {'n_neighbors': 70, 'n_components': 15, 'min_dist': 0.019179033462440154, 'min_cluster_size': 5, 'min_samples': 10}. Best is trial 23 with value: 0.7687163949012756.

Trial 48: Silhouette=0.5795 | Кластеров=33 | Шум=32.6% | NN=70, MC=5

[I 2026-05-29 19:15:31,848] Trial 49 finished with value: 0.5679279565811157 and parameters: {'n_neighbors': 5, 'n_components': 3, 'min_dist': 0.03590600695351351, 'min_cluster_size': 30, 'min_samples': 5}. Best is trial 23 with value: 0.7687163949012756.

Trial 49: Silhouette=0.5679 | Кластеров=16 | Шум=13.2% | NN=5, MC=30

Лучшие параметры: {'n_neighbors': 5, 'n_components': 20, 'min_dist': 0.019360479975685907, 'min_cluster_size': 5, 'min_samples': 10}

In [ ]:
optuna.visualization.plot_optimization_history(study)

In [16]:
umap_model = umap.UMAP(
    n_neighbors=5,
    n_components=20,
    min_dist=0.019,
    metric='euclidean',
    random_state=42
)

In [17]:
hdbscan_model = hdbscan.HDBSCAN(
    min_cluster_size=5,
    min_samples=10,
    gen_min_span_tree=True,
    metric='euclidean',
    cluster_selection_method='eom',
)

In [18]:
representation_model = {"MMR": MaximalMarginalRelevance(diversity=0.5)}

In [19]:
topic_model = BERTopic(
    language='russian',
    embedding_model=None,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    ctfidf_model=ctfidf_model,
    representation_model=representation_model
)

In [20]:
topic_model.save("/content/drive/MyDrive/TextClust/my_model", serialization="safetensors")

TypeError: 'NoneType' object is not iterable

In [ ]:
topic_model = BERTopic.load("/content/drive/MyDrive/TextClust/my_model")

2026-05-29 19:49:49,433 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

In [21]:
topics, _ = topic_model.fit_transform(df['document_text_preproc'].astype(str).tolist(), embeddings=embed_norm)

In [ ]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,MMR,Representative_Docs
0,-1,110,-1_проверке_комиссии_труда_письмо,"[проверке, комиссии, труда, письмо, исходящее, исходящее письмо, комиссии проверке, назначении комиссии, письмо директору, подшипников]","[проверке, комиссии, труда, письмо, исходящее, исходящее письмо, комиссии проверке, назначении комиссии, письмо директору, подшипников, случае, состояния, приказ назначении, назначении, мест, рабочих мест, путей, приказ, просим, уровня, цехе, директору, условиям, лимиты, аттестации рабочих, мест условиям, условиям труда, рабочих, организовать замеры, аттестации]","[ПРИКАЗ №1690. О проведении аттестации рабочих мест по условиям труда. Организовать замеры уровня вибрации на участках прессового оборудования цеха №1. Срок исполнения — до 15.12. Ответственный — инж. по ОТ., ПРИКАЗ №890. О проведении аттестации рабочих мест по условиям труда. Организовать замеры уровня вибрации на участках прессового оборудования. Срок исполнения — до 15.12. Ответственный — инж. по ОТ., ПРИКАЗ №1290. О проведении аттестации рабочих мест по условиям труда. Организовать замер..."
1,0,78,0_нач омтс_омтс_закупка_нач,"[нач омтс, омтс, закупка, нач, требуется закупка, главному бухгалтеру, бухгалтеру, бухгалтеру нач, омтс прошу, срочно требуется]","[нач омтс, омтс, закупка, нач, требуется закупка, главному бухгалтеру, бухгалтеру, бухгалтеру нач, омтс прошу, срочно требуется, срочно, прошу выделить, выделить, служебная записка, служебная, записка, требуется, средства, омтс нач, литров, прошу, участка, выделить денежные, денежные средства, денежные, нач транспортного, транспортного, отдел снабжения, записка главному, финансовому]","[СЛУЖЕБНАЯ ЗАПИСКА. Главному бухгалтеру. От нач. ОМТС. Прошу выделить денежные средства на оплату счета №112 за приобретение 100 литров СОЖ марки Blaser для работы на высокоскоростных станках ЧПУ., СЛУЖЕБНАЯ ЗАПИСКА. Главному бухгалтеру. От нач. ОМТС. Прошу выделить денежные средства в размере руб. на приобретение измерительного инструмента (микрометры, штангенциркули) для нужд цеха №1., СЛУЖЕБНАЯ ЗАПИСКА. Главному бухгалтеру. От нач. ОМТС. Прошу выделить денежные средства на оплату счета №9..."
2,1,44,1_директору ит_ит нач_ит_записка директору,"[директору ит, ит нач, ит, записка директору, директору, бухгалтерии, пдо прошу, прошу, нач бухгалтерии, бухгалтерии прошу]","[директору ит, ит нач, ит, записка директору, директору, бухгалтерии, пдо прошу, прошу, нач бухгалтерии, бухгалтерии прошу, нач пдо, пдо, настроить, прошу настроить, доступ, системе, прошу предоставить, служебная записка, служебная, записка, нач, прошу приобрести, отдела, приобрести, дополнительный модуль, модуль, кадров прошу, автоматизации, дополнительный, ведущему]","[СЛУЖЕБНАЯ ЗАПИСКА. Директору по ИТ. От нач. отдела кадров. Прошу приобрести дополнительный модуль 'Подбор персонала' для системы 1С в целях автоматизации процесса обработки резюме кандидатов., СЛУЖЕБНАЯ ЗАПИСКА. Директору по ИТ. От нач. отдела кадров. Прошу приобрести дополнительный модуль 'Подбор персонала' для системы 1С в целях автоматизации процесса обработки резюме., СЛУЖЕБНАЯ ЗАПИСКА. Директору по ИТ. От нач. отдела кадров. Прошу приобрести дополнительный модуль 'Подбор персонала' для..."
3,2,41,2_назначить_ответственным_приказ назначении_назначении,"[назначить, ответственным, приказ назначении, назначении, ответственного, назначении ответственного, исправное, исправное состояние, состояние, ответственного исправное]","[назначить, ответственным, приказ назначении, назначении, ответственного, назначении ответственного, исправное, исправное состояние, состояние, ответственного исправное, назначить мастера, назначении ответственных, приказ закреплении, закреплении, ответственных, систем, закрепить, эксплуатацию, механика, приказ, службой, содержание, мастера, состояние систем, ответственным проверку, ответственной, своевременную, ответственных содержание, ведение, проверку]","[ПРИКАЗ №1805. О назначении ответственных за содержание и эксплуатацию систем вентиляции в цехе №4. Назначить мастера участка Сидорова П.А. ответственным за своевременную очистку пылеулавливающих агрегатов и замену фильтров., ПРИКАЗ №1830. О назначении ответственного за исправное состояние систем пожаротушения в электрощитовых. Назначить главного энергетика Соколова И.М. ответственным за проверку модулей газового пожаротушения., ПРИКАЗ №1630. О назначении ответственного за исправное состояни..."
4,3,35,3_комиссию_инвентаризации_создать_создать комиссию,"[комиссию, инвентаризации, создать, создать комиссию, приказ проведении, проведении, проведении инвентаризации, срок, срок предоставления, предоставления]","[комиссию, инвентаризации, создать, создать комиссию, приказ проведении, проведении, проведении инвентаризации, срок, срок предоставления, предоставления, комиссии, наличия, проведении внутреннего, предоставления отчета, внутреннего аудита, внутреннего, отчета, приказ, остатков, аудита, комиссию сверки, проверить, комиссию проверки, аудита системы, сверки, инструмента, составе, председатель, комиссии приемке, системы охраны]","[ПРИКАЗ №820. О проведении инвентаризации инструмента на центральном складе. Создать комиссию в составе: бух. Иванова, нач. склада Петров, инженер Сидоров. Срок проведения — с 20.11 по 25.11., ПРИКАЗ №1820. О проведении инвентаризации остатков сварочной проволоки и электродов. Создать комиссию для сверки фактических остатков на складах цехов №1 и №3 с данными бухгалтерского учета. Срок предоставления ведомостей — 20.11., ПРИКАЗ №1620. О проведении инвентаризации остатков сварочной проволоки ..."
5,4,32,4_инженеру нач_главному инженеру_инженеру_строя,"[инженеру нач, главному инженеру, инженеру, строя, сообщаю, требуется, производству, директору производству, записка главному, выходе]","[инженеру нач, главному инженеру, инженеру, строя, сообщаю, требуется, производству, директору производству, записка главному, выходе, выходе строя, главному, станка, замена, инв требуется, инв, сообщаю выходе, закупка, информирую, участка, служебная записка, служебная, записка, цеха, нач участка, записка директору, требуется закупка, наблюдается, нач ремонтного, износе]","[СЛУЖЕБНАЯ ЗАПИСКА. Главному инженеру. От нач. инструментального цеха. Сообщаю о выходе из строя заточного станка. Требуется закупка алмазных кругов и замена шпиндельного узла. Ремонт силами цеха невозможен., СЛУЖЕБНАЯ ЗАПИСКА. Главному инженеру. От нач. ремонтного участка. Сообщаю о критическом износе направляющих станка мод. 1М63 (инв. №12). Требуется проведение капитального ремонта., СЛУЖЕБНАЯ ЗАПИСКА. Главному инженеру. От нач. ремонтного участка. Сообщаю о критическом износе направляющи..."
6,5,32,5_выплатить_премию_премировании_приказ премировании,"[выплатить, премию, премировании, приказ премировании, списку, выплатить премию, списку приказ, итогам, согласно списку, согласно]","[выплатить, премию, премировании, приказ премировании, списку, выплатить премию, списку приказ, итогам, согласно списку, согласно, приказ поощрении, поощрении, размере, премию размере, вознаграждение, приказ награждении, награждении, приказ, снижение, результатам, добросовестный, премировать, добросовестный труд, труд, производства, приказываю выплатить, премировании высокое, приложенному списку, экономию, показал]","[ПРИКАЗ №975. О награждении почетными грамотами в связи с Днем машиностроителя. За многолетний добросовестный труд наградить передовиков производства согласно приложенному списку и выплатить вознаграждение., ПРИКАЗ №1235. О премировании за экономию материалов. По итогам квартала на заготовительном участке достигнуто снижение отходов листового проката на 8%. Выплатить бригаде премию согласно списку., ПРИКАЗ №835. О премировании за экономию материалов. По итогам квартала на заготовительном уча..."
7,6,31,6_кадров нач_цеха прошу_кадров_нач цеха,"[кадров нач, цеха прошу, кадров, нач цеха, отдела кадров, нач отдела, директору персоналу, прошу рассмотреть, персоналу мастера, разряда]","[кадров нач, цеха прошу, кадров, нач цеха, отдела кадров, нач отдела, директору персоналу, прошу рассмотреть, персоналу мастера, разряда, персоналу, рассмотреть кандидатуру, кандидатуру, токаря, рассмотреть, цеха, слесаря, прошу, участка прошу, иванова, отдела, записка нач, мастера, нач, кандидатуру токаря, успешным, связи успешным, связи, записка, мастера мех]","[СЛУЖЕБНАЯ ЗАПИСКА. Директору по персоналу. От мастера мех. участка. Прошу рассмотреть кандидатуру токаря Иванова В.С. на получение 5-го разряда. Теоретический экзамен и пробная работа сданы успешно., СЛУЖЕБНАЯ ЗАПИСКА. Директору по персоналу. От мастера мех. участка. Прошу рассмотреть кандидатуру токаря Петрова С.А. на получение 4-го разряда в связи с успешным освоением обработки нержавеющих сталей на станках с ЧПУ., СЛУЖЕБНАЯ ЗАПИСКА. Директору по персоналу. От мастера мех. участка. Прошу ..."
8,7,30,7_эко_руководителю эко_исходящее_исходящее письмо,"[эко, руководителю эко, исходящее, исходящее письмо, письмо, письмо руководителю, руководителю, управления, росприроднадзора направляем, управления росприроднадзора]","[эко, руководителю эко, исходящее, исходящее письмо, письмо, письмо руководителю, руководителю, управления, росприроднадзора направляем, управления росприроднадзора, росприроднадзора, письмо адрес, адрес, направляем, просим, адрес управления, отчет, просим провести, отходов, провести замеры, лимитов, направляем отчет, веществ, квартал года, iii квартал, нарушений, зоны, iii, адрес регионального, регионального]","[ИСХОДЯЩЕЕ ПИСЬМО. Руководителю ООО 'Эко-Мониторинг'. Просим провести замеры концентрации вредных веществ в воздухе рабочей зоны на участке пайки в связи с модернизацией системы местной вытяжной вентиляции., ИСХОДЯЩЕЕ ПИСЬМО. В адрес регионального управления Росприроднадзора. Направляем отчет по форме 2-ТП (отходы) за III квартал 2023 года. Нарушений установленных лимитов размещения промышленных отходов не выявлено., ИСХОДЯЩЕЕ ПИСЬМО. В адрес регионального управления Росприроднадзора. Направ..."
9,8,29,8_отдела_юридического отдела_нач юридического_юридического,"[отдела, юридического отдела, нач юридического, юридического, прошу подготовить, менеджера, отдела менеджера, подготовить, юридический отдел, отдел отдела]","[отдела, юридического отдела, нач юридического, юридического, прошу подготовить, менеджера, отдела менеджера, подготовить, юридический отдел, отдел отдела, записка юридический, юридический, прошу проверить, подготовить проект, проект, прошу, отдел, записка нач, закупкам прошу, менеджера закупкам, договору, отдела сбыта, сбыта, сбыта прошу, соглашения, проверить, закупкам, служебная, служебная записка, записка]","[СЛУЖЕБНАЯ ЗАПИСКА. Нач. юридического отдела. От менеджера по закупкам. Прошу проверить юридическую чистоту правоустанавливающих документов нового поставщика инструмента ООО 'Резец' перед подписанием контракта., СЛУЖЕБНАЯ ЗАПИСКА. Нач. юридического отдела. От менеджера по закупкам. Прошу подготовить проект дополнительного соглашения с ООО 'ПромСталь' о возможности оплаты товара векселями предприятия., СЛУЖЕБНАЯ ЗАПИСКА. В юридический отдел. От отдела сбыта. Прошу подготовить проект дополните..."
10,9,29,9_охраны_отдела нач_ит отдела_нач ит,"[охраны, отдела нач, ит отдела, нач ит, начальнику охраны, записка начальнику, прошу разрешить, нач охраны, разрешить, начальнику]","[охраны, отдела нач, ит отдела, нач ит, начальнику охраны, записка начальнику, прошу разрешить, нач охраны, разрешить, начальнику, ит, номер, автомобиля, записка нач, разрешить выезд, выезд, прошу, охраны прошу, видеонаблюдения, нач, охраны требуется, отдела, готовой продукции, готовой, служебная записка, служебная, записка, зав, зав складом, кпп]","[СЛУЖЕБНАЯ ЗАПИСКА. Начальнику охраны. От нач. склада готовой продукции. Прошу разрешить выезд автомобиля ГАЗель (номер Е444КХ) после 20:00 для доставки срочного груза на железнодорожный вокзал., СЛУЖЕБНАЯ ЗАПИСКА. Начальнику охраны. От нач. склада готовой продукции. Прошу разрешить выезд автомобиля КАМАЗ (номер В999ВВ) 15.11 в 06:00 для доставки крупногабаритного груза на объект заказчика в г. Уфа., СЛУЖЕБНАЯ ЗАПИСКА. Начальнику охраны. От нач. склада готовой продукции. Прошу разрешить выез..."
11,10,27,10_запретить_работ_порядке проведения_проведения,"[запретить, работ, порядке проведения, проведения, приказ запрете, наряда допуска, запрете, наряда, оформления, приказ порядке]","[запретить, работ, порядке проведения, проведения, приказ запрете, наряда допуска, запрете, наряда, оформления, приказ порядке, порядке, допуска, оформления наряда, категорически запретить, нарушителей, категорически, сварочных работ, использования, запрете использования, вне, сварочных, огневых, проведения огневых, огневых работ, наличия, высоте, запретить эксплуатацию, проведения сварочных, проведения работ, личных]","[ПРИКАЗ №1440. О порядке проведения сварочных работ на временных постах. Категорически запретить сварку вне цеха без наличия экрана, средств пожаротушения и оформления наряда-допуска., ПРИКАЗ №1640. О порядке проведения огневых работ на высоте. Категорически запретить проведение сварки на высоте более 1.8 м без оформления наряда-допуска, наличия страховочного пояса и огнеупорного полотна внизу., ПРИКАЗ №1840. О порядке проведения огневых работ на высоте. Категорически запретить проведение св..."
12,11,27,11_службы го_го чс_чс_го,"[службы го, го чс, чс, го, нач службы, записка нач, службы, сообщаю необходимости, необходимости, чс мастера]","[службы го, го чс, чс, го, нач службы, записка нач, службы, сообщаю необходимости, необходимости, чс мастера, сообщаю, замены, нач, электроцеха срочно, нач электроцеха, электроцеха, прошу обеспечить, освещения, огнетушителей, омтс нач, штук, чс нач, светодиодных, освещения территории, территории, срочно требуется, срочно, нач омтс, омтс, оу]","[СЛУЖЕБНАЯ ЗАПИСКА. Нач. службы ГО и ЧС. От мастера инструментального участка. Сообщаю о необходимости замены 5 огнетушителей ОУ-5, у которых истек срок эксплуатации. Прошу обеспечить замену до конца недели., СЛУЖЕБНАЯ ЗАПИСКА. Нач. службы ГО и ЧС. От мастера участка гальваники. Сообщаю о необходимости перезарядки огнетушителей ОУ-5 в количестве 8 штук. Срок очередной проверки истекает 25.11., СЛУЖЕБНАЯ ЗАПИСКА. Нач. службы ГО и ЧС. От мастера участка гальваники. Сообщаю о необходимости пере..."
13,12,25,12_металл_исходящее письмо_письмо_исходящее,"[металл, исходящее письмо, письмо, исходящее, требуем, руководителю, письмо руководителю, уведомляем, партию, поставки]","[металл, исходящее письмо, письмо, исходящее, требуем, руководителю, письмо руководителю, уведомляем, партию, поставки, поставка направляем, руководителю металл, круга, претензию, поставка, акт, проката, листового проката, листового, заменить партию, ржавого, адрес металл, проката марка, поставки ржавого, некондиционном товаре, некондиционном, марка требуем, ржавого листового, акт некондиционном, товаре заменить]","[ИСХОДЯЩЕЕ ПИСЬМО. В адрес ООО 'Металл-Поставка'. Направляем претензию по факту поставки ржавого листового проката (марка ст3, 10 мм). Требуем составить акт о некондиционном товаре и заменить партию., ИСХОДЯЩЕЕ ПИСЬМО. В адрес ООО 'Металл-Поставка'. Направляем претензию по факту поставки ржавого листового проката (марка ст3, 10 мм). Требуем составить акт о некондиционном товаре и заменить партию., ИСХОДЯЩЕЕ ПИСЬМО. В адрес ООО 'Металл-Поставка'. Направляем претензию по факту поставки ржавого..."
14,13,23,13_просим_масла_пресса_директору завода,"[просим, масла, пресса, директору завода, письмо директору, исходящее письмо, письмо, исходящее, сроки, литров]","[просим, масла, пресса, директору завода, письмо директору, исходящее письмо, письмо, исходящее, сроки, литров, изготовления, просим рассмотреть, tellus, уплотнений, shell tellus, shell, нашим, литров масла, возможность изготовления, завода, рассмотреть возможность, возможность, прессового, сталь, листогибочного пресса, сообщаю протечке, критический исходящее, масла гидросистеме, масла марки, протечке]","[ИСХОДЯЩЕЕ ПИСЬМО. Директору завода 'Пресс-Маш'. Просим рассмотреть возможность изготовления запасных частей (гидроцилиндр) для пресса П6330 по нашим эскизам. Просим уточнить сроки., СЛУЖЕБНАЯ ЗАПИСКА. Главному инженеру. От нач. участка гидравлики. Сообщаю о протечке масла в гидросистеме листогибочного пресса Amada. Требуется закупка набора уплотнений и 100 литров масла марки Shell Tellus., СЛУЖЕБНАЯ ЗАПИСКА. Главному инженеру. От нач. участка гидравлики. Сообщаю о протечке масла в гидросист..."
15,14,23,14_нач пдо_пдо_информирую_заказа,"[нач пдо, пдо, информирую, заказа, дня, пдо мастера, рабочих дня, информирую задержке, пдо нач, задержке]","[нач пдо, пдо, информирую, заказа, дня, пдо мастера, рабочих дня, информирую задержке, пдо нач, задержке, записка нач, довожу, довожу сведения, сведения, участка, рабочих, заготовок, литья, валов, литья корпус, участка информирую, корпус, ленточнопильного, задерживается, ленточнопильного станка, сдвигается, участка довожу, дня служебная, мастера, нач]","[СЛУЖЕБНАЯ ЗАПИСКА. Нач. ПДО. От мастера мех. участка. Информирую о задержке изготовления валов из-за неисправности ленточнопильного станка. Срок сдачи заказа сдвигается на два рабочих дня., СЛУЖЕБНАЯ ЗАПИСКА. Нач. ПДО. От мастера участка сборки. Довожу до сведения, что из-за брака литья (корпус насоса) выполнение заказа №88 задерживается на 4 рабочих дня. Прошу уведомить заказчика., СЛУЖЕБНАЯ ЗАПИСКА. Нач. ПДО. От мастера участка сборки. Довожу до сведения, что из-за брака литья (корпус нас..."
16,15,23,15_сиз_мастерам_приказ усилении_усилении,"[сиз, мастерам, приказ усилении, усилении, органов, усилении контроля, обеспечить, защитных, выдачи, средств]","[сиз, мастерам, приказ усилении, усилении, органов, усилении контроля, обеспечить, защитных, выдачи, средств, порядке выдачи, сиз органов, контроля использованием, приказ порядке, порядке, защиты, использованием, контроля, выдачи защитных, органов дыхания, персоналом, дыхания, средств защиты, респираторов, смен, нормам, использованием сиз, органов слуха, мастерам смен, слуха]","[ПРИКАЗ №760. Об усилении контроля за использованием СИЗ органов дыхания в литейном цехе. Мастерам смен обеспечить обязательное ношение респираторов персоналом при проведении операций выбивки опок., ПРИКАЗ №1625. О порядке выдачи защитных очков и масок сотрудникам малярного участка. Обеспечить наличие СИЗ на рабочих местах согласно утвержденным нормам. Мастерам контролировать использование средств защиты в течение всей смены., ПРИКАЗ №1825. О порядке выдачи защитных очков и масок сотрудникам..."
17,16,21,16_главному механику_механику_наблюдается_механику мастера,"[главному механику, механику, наблюдается, механику мастера, записка главному, главному, требуется замена, ремней, работе, замена]","[главному механику, механику, наблюдается, механику мастера, записка главному, главному, требуется замена, ремней, работе, замена, мастера цеха, проскальзывание, наблюдается проскальзывание, мастера, станка, механику механика, цеха сообщаю, требуется, цеха, сообщаю, инв, механика цеха, цеха требуется, замена клиновых, клиновых ремней, клиновых, механика, компрессорной, необходимости замены, ремонта]","[СЛУЖЕБНАЯ ЗАПИСКА. Главному механику. От механика цеха №5. Требуется замена клиновых ремней на компрессорной установке №2. Наблюдается проскальзывание и потеря производительности. Текущий остаток ремней на складе отсутствует., СЛУЖЕБНАЯ ЗАПИСКА. Главному механику. От механика цеха №5. Требуется замена клиновых ремней на компрессорной установке №2. Наблюдается проскальзывание и потеря производительности. На складе ремни отсутствуют., СЛУЖЕБНАЯ ЗАПИСКА. Главному механику. От механика цеха №5...."

In [ ]:
# метрики
calculate_clustering_metrics(topic_model.umap_model.transform(embed_norm),topics)
print(f"DBCV: {(topic_model.hdbscan_model.relative_validity_):.2f}")

Кол-во тем: 38
Шум: 110 из 1000 (11.0%)
Silhouette: 0.751
Calinski-Harabasz: 5094
Davies-Bouldin: 0.341
DBCV: 0.41

In [ ]:
# используем n_components=2, чтобы можно было нарисовать точки на плоскости
reduced_embeddings_2d = umap.UMAP(
    n_neighbors=15,
    n_components=2,
    metric='euclidean',
    random_state=42
).fit_transform(embed)

topic_model.visualize_documents(df['document_text_preproc'], reduced_embeddings=reduced_embeddings_2d, hide_annotations=True)

In [22]:
# распределяем шум
new_topics = topic_model.reduce_outliers(
    documents=df['document_text_preproc'].tolist(),
    topics=topics,
    strategy="embeddings", # явно указываем стратегию по эмбеддингам
    embeddings=embed_norm,
    threshold=0.6
)
topic_model.update_topics(df['document_text_preproc'].tolist(), topics=new_topics, top_n_words=10)

2026-05-30 10:56:24,627 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

In [ ]:
# визуализация после распределения
topic_model.visualize_documents(df['document_text_preproc'], reduced_embeddings=reduced_embeddings_2d, hide_annotations=True)

In [ ]:
# метрики после распределения шума
calculate_clustering_metrics(topic_model.umap_model.transform(embed_norm),new_topics)
print(f"DBCV: {(topic_model.hdbscan_model.relative_validity_):.2f}")

Кол-во тем: 38
Шум: 0 из 1000 (0.0%)
Silhouette: 0.539
Calinski-Harabasz: 577
Davies-Bouldin: 1.055
DBCV: 0.41

In [23]:
topic_info = topic_model.get_topic_info()
topic_info.to_csv("/content/drive/MyDrive/TextClust/topic_info_mmr.csv", index=False)

## Получение тем LLM

In [3]:
topic_info = pd.read_csv("/content/drive/MyDrive/TextClust/topic_info_mmr.csv")
topic_model = BERTopic.load("/content/drive/MyDrive/TextClust/my_model")

2026-05-30 11:47:42,127 - BERTopic - WARNING: You are loading a BERTopic model without explicitly defining an embedding model. If you want to also load in an embedding model, make sure to use `BERTopic.load(my_model, embedding_model=my_embedding_model)`.

In [5]:
# Очистка памяти
gc.collect()
torch.cuda.empty_cache()

model_id = "Qwen/Qwen2.5-14B"

bnb_config = BitsAndBytesConfig(
    load_in_8bit=True
)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(
    model_id,
    trust_remote_code=True
)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map={"": 0},              # Жесткая посадка на GPU:0
    low_cpu_mem_usage=True,          # Экономия RAM при инициализации
    trust_remote_code=True
)

config.json:   0%|          | 0.00/664 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.23k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/47.5k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

In [ ]:
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=20,
    max_length=None,       # Явно сбрасываем max_length, чтобы убрать варнинг
    return_full_text=False,
    do_sample=True,      # Включаем сэмплирование (обязательно для работы temperature)
    temperature=0.3,     # Оптимально для строгого следования инструкциям
    top_p=0.9,
)

In [ ]:
llm = HuggingFacePipeline(
    pipeline=pipe,
    pipeline_kwargs={
        "tokenizer": tokenizer,
        # Добавляем перенос строки, чтобы модель не генерировала лишний текст
        "stop_strings": ["<|im_end|>", "<|endoftext|>", "\n"]
    }
)

In [ ]:
template = """<|im_start|>system
Ты — эксперт по документообороту в машиностроении. Твоя задача — изучить ключевые слова документов завода и назвать тему.

Правила:
1. Пиши ТОЛЬКО название темы (1, 2 или максимум 3 слова).
2. Используй аббревиатуры (ОМТС, ПДО, ИТ, ЧС, ОТ и ТБ).
3. Никаких вводных слов, никаких глаголов и фраз вроде "приказ о...", "записка о...".
4. Пиши строго существительными в именителном падеже (например: "Материально-техническое снабжение", "Входной контроль").

Примеры:
Ключевые слова: график, дежурство, начальник, цех, сменность
Тема: График дежурств персонала

Ключевые слова: склад, металл, закупка, поставщик, снабжение
Тема: Материально-техническое снабжение
<|im_end|>
<|im_start|>user
Назови краткую тему (1-3 слова) для ключевых слов: {keywords}
<|im_end|>
<|im_start|>assistant
Тема: """


prompt = PromptTemplate.from_template(template)
chain = prompt | llm

In [22]:
topic_info = topic_model.get_topic_info()

# Словарь для хранения результатов: {ID_кластера: "сгенерированная_тема"}
cluster_themes = {}

for index, row in topic_info.iterrows():
    topic_id = row['Topic']

    # Пропускаем выбросы/шум
    if topic_id == -1:
        cluster_themes[topic_id] = "выбросы (шум)"
        continue

    # Извлекаем список слов MMR
    mmr_keywords_list = row['Representation']

    # Очищаем и лемматизируем список с помощью Natasha
    filtered_list = mmr_keywords_list

    # Объединяем чистые леммы
    keywords_string = ", ".join(filtered_list)

    # Запуск генерации через LangChain цепочку
    try:
        generated_theme = chain.invoke({"keywords": keywords_string})

        # Очищаем от возможных пробелов по краям
        clean_theme = generated_theme.strip().strip('."\'`').lower()
        cluster_themes[topic_id] = clean_theme

        print(f"Кластер {topic_id}: {clean_theme}")

    except Exception as e:
        print(f"Ошибка при обработке кластера {topic_id}: {e}")
        cluster_themes[topic_id] = "ошибка генерации"

# Добавление сгенерированных тем обратно в датафрейм BERTopic
topic_info['Generated_Theme'] = topic_info['Topic'].map(cluster_themes)

Кластер 0: закупка, срочно требуется закуп заготовок, срочно требуется закуп заготовок, срочно требуется закуп
Кластер 1: , записка, записка, записка, записка, 'записка'
assistant:
Кластер 2: , исправное состояние, исправное состояние, исправное состояние, ответственного, исправное состояние,

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Кластер 3: , срок, срок, срок, срок, срок, срок, срок, срок, срок, срок
Кластер 4: из строя, выход из строя, выход из строя, выход из строя, выход из машиностро
Кластер 5: приказу, согласно приказу, согласно приказу, согласно приказу, согласно приказу, согласно

KeyboardInterrupt:

In [ ]:

# Извлекаем топ-слова для всех топиков (исключая шум -1) из результатов MMR
all_topics = topic_model.get_topics()
topic_words = [
    [word for word, _ in all_topics[topic]] 
    for topic in all_topics if topic != -1
]

# Полная токенизация и лемматизация всего корпуса документов
cleaned_corpus_strings = clean_text_lemma(all_docs_list)
tokenized_corpus = [doc.lower().split() for doc in cleaned_corpus_strings]

# Создаем структуру словаря Gensim
dictionary = Dictionary(tokenized_corpus)


# coherence score
coherence_model = CoherenceModel(
    topics=topic_words, 
    texts=tokenized_corpus, 
    dictionary=dictionary, 
    coherence='c_v'
)
coherence_score = coherence_model.get_coherence()
print(f"Topic Coherence (C_V): {coherence_score:.4f}")


# topic diversity
def calculate_topic_diversity(topics, topk=10):
    all_words = []
    for topic in topics:
        all_words.extend(topic[:topk])
    if not all_words:
        return 0.0
    return len(set(all_words)) / len(all_words)

diversity_score = calculate_topic_diversity(topic_words, topk=10)
print(f"Topic Diversity (Top-10): {diversity_score:.4f}")

In [ ]:
topic_info

In [ ]:
topic_info.to_csv('/content/drive/MyDrive/TextClust/df_with_topics.csv', index=False, encoding='utf-8-sig')